name: Deploy mxsm website to GitHub

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  test-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm update --legacy-peer-deps
      - name: Test build website
        run: |
          npm run clear
          npm run build
  deploy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "ljbmxsm@gmail.com"
          git config --global user.name "mxsm"
          npm update --legacy-peer-deps
          npm run clear
          npm run build
          npm run deploy
