name: blog.ljbmxsm.com

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: mxsm/mxsm-website@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: mxsm/mxsm.github.io@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.LJBMXSM }}
          publish_dir: ./public
